Acme\StoreBundle\Entity\Feedbacks:
    type: entity
    table: feedbacks
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        message:
            type: string
            length: 255
            fixed: false
            nullable: false
    manyToOne:
        owner:
            targetEntity: Users
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                owner:
                    referencedColumnName: id
            orphanRemoval: false
        viewer:
            targetEntity: Users
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                viewer:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
