Acme\StoreBundle\Entity\Screenshots:
    type: entity
    table: screenshots
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        thumb:
            type: string
            length: 255
            fixed: false
            nullable: false
        large:
            type: string
            length: 255
            fixed: false
            nullable: false
    lifecycleCallbacks: {  }
