Acme\StoreBundle\Entity\UserTokens:
    type: entity
    table: user_tokens
    fields:
        id:
            id: true
            type: integer
            unsigned: true
            nullable: false
            generator:
                strategy: IDENTITY
        userAgent:
            type: string
            length: 40
            fixed: false
            nullable: false
            column: user_agent
        token:
            type: string
            length: 32
            fixed: false
            nullable: false
        created:
            type: integer
            unsigned: true
            nullable: false
        expires:
            type: integer
            unsigned: true
            nullable: false
    manyToOne:
        user:
            targetEntity: Users
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
