parameters:
#    clgt_user.example.class: Clgt\UserBundle\Example

services:
#    clgt_user.example:
#        class: %clgt_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
