clgt_theme_homepage:
    pattern:  /
    defaults: { _controller: ClgtThemeBundle:Default:index }
    
clgt_theme_login:
    resource: "@ClgtThemeBundle/Controller/LoginController.php"
    type: annotation
