acme_store_homepage:
    path:  /hello/
    defaults: { _controller: AcmeStoreBundle:Default:index }

acme_store_user_singin:
    path: /signin
    defaults: { _controller: AcmeStoreBundle:User:signin }

acme_store_user_signup:
    path: /signup
    defaults: { _controller: AcmeStoreBundle:User:signup }
