Payments:
    type: entity
    table: payments
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        taxName:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: tax_name
        taxNumber:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: tax_number
        paypal:
            type: string
            length: 255
            fixed: false
            nullable: false
    manyToOne:
        user:
            targetEntity: Users
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
        organization:
            targetEntity: Organizations
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                organization_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
