Templates:
    type: entity
    table: templates
    fields:
        id:
            id: true
            type: string
            length: 15
            fixed: false
            nullable: false
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 255
            fixed: false
            nullable: false
        slug:
            type: string
            length: 255
            fixed: false
            nullable: false
        price:
            type: float
            nullable: false
        exclusivity:
            type: boolean
            nullable: false
        license:
            type: string
            length: 255
            fixed: false
            nullable: false
        status:
            type: boolean
            nullable: false
        isDeploy:
            type: boolean
            nullable: false
            column: is_deploy
        created:
            type: integer
            unsigned: false
            nullable: false
        updated:
            type: integer
            unsigned: false
            nullable: true
        description:
            type: text
            nullable: false
    manyToMany:
        layout:
            targetEntity: Layouts
            cascade: {  }
            mappedBy: null
            inversedBy: template
            joinTable:
                name: templates_layouts
                joinColumns:
                    -
                        name: template_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: layout_id
                        referencedColumnName: id
            orderBy: null
        tag:
            targetEntity: Tags
            cascade: {  }
            mappedBy: null
            inversedBy: template
            joinTable:
                name: templates_tags
                joinColumns:
                    -
                        name: template_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: tag_id
                        referencedColumnName: id
            orderBy: null
    manyToOne:
        user:
            targetEntity: Users
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
        screenshot:
            targetEntity: Screenshots
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                screenshot_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
