Users:
    type: entity
    table: users
    fields:
        id:
            id: true
            type: integer
            unsigned: true
            nullable: false
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 255
            fixed: false
            nullable: false
        picture:
            type: string
            length: 255
            fixed: false
            nullable: false
        banner:
            type: string
            length: 255
            fixed: false
            nullable: false
        email:
            type: string
            length: 127
            fixed: false
            nullable: false
        username:
            type: string
            length: 32
            fixed: false
            nullable: false
        password:
            type: string
            length: 64
            fixed: true
            nullable: false
        balance:
            type: float
            nullable: false
        logins:
            type: integer
            unsigned: true
            nullable: true
        lastLogin:
            type: integer
            unsigned: true
            nullable: true
            column: last_login
        created:
            type: integer
            unsigned: true
            nullable: true
        paymentAccount:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: payment_account
    manyToMany:
        role:
            targetEntity: Roles
            cascade: {  }
            mappedBy: null
            inversedBy: user
            joinTable:
                name: roles_users
                joinColumns:
                    -
                        name: user_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: role_id
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
