acme_user_signin:
    pattern:  /signin
    defaults: { _controller: AcmeUserBundle:Default:signin }

acme_user_signout:
    pattern:  /singout
    defaults: { _controller: AcmeUserBundle:Default:signout }
