acme_user_register:
    pattern:  /register
    defaults: { _controller: AcmeUserBundle:Account:register }
acme_user_create:
    pattern: /create
    defaults: { _controller: AcmeUserBundle:Account:create }